# Generated by Django 4.2.13 on 2025-02-21 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='teacher_break',
            field=models.PositiveIntegerField(default=15),
        ),
    ]
