# Generated by Django 4.2.13 on 2025-01-27 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0011_course_group_size_course_is_group'),
        ('teacher', '0024_alter_teacher_school'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=12, unique=True)),
                ('booked_datetime', models.DateTimeField()),
                ('status', models.CharField(choices=[('PENTE', 'PendingTeacher'), ('CON', 'Confirmed'), ('COM', 'Completed'), ('CAN', 'Canceled'), ('AVA', 'Available')], default='PENTE', max_length=5)),
                ('number_of_client', models.IntegerField(default=0)),
                ('notified', models.BooleanField(default=False)),
                ('student_event_id', models.CharField(blank=True, null=True)),
                ('teacher_event_id', models.CharField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson', to='school.course')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson', to='teacher.teacher')),
            ],
        ),
    ]
