# Generated by Django 4.2.13 on 2025-01-27 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0026_alter_lesson_teacher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='booked_datetime',
            new_name='datetime',
        ),
    ]
