# Generated by Django 4.2.13 on 2025-01-31 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0028_alter_lesson_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='course',
        ),
        migrations.DeleteModel(
            name='TeacherCourses',
        ),
    ]
