# Generated by Django 4.2.13 on 2025-02-01 06:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0030_availabletime'),
    ]

    operations = [
        migrations.AddField(
            model_name='availabletime',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
