# Generated by Django 4.2.13 on 2025-01-31 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0030_availabletime'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='available_time',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lesson', to='teacher.availabletime'),
        ),
    ]
