# Generated by Django 4.2.13 on 2025-02-01 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0031_availabletime_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='available_times',
            field=models.JSONField(default=list),
        ),
        migrations.DeleteModel(
            name='AvailableTime',
        ),
    ]
