# Generated by Django 4.2.13 on 2025-01-31 15:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0031_lesson_available_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='availabletime',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='available_time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson', to='teacher.availabletime'),
        ),
    ]
