# Generated by Django 4.2.13 on 2025-02-02 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0021_alter_course_school'),
        ('teacher', '0032_teacher_available_times_delete_availabletime'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='course',
            field=models.ManyToManyField(related_name='teacher', to='school.course'),
        ),
    ]
