# Generated by Django 4.2.13 on 2025-02-03 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0034_remove_teacher_available_times_availabletime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='status',
            field=models.CharField(choices=[('PENTE', 'PendingTeacher'), ('CON', 'Confirmed'), ('COM', 'Completed'), ('CAN', 'Canceled')], default='PENTE', max_length=5),
        ),
    ]
