# Generated by Django 4.2.13 on 2025-01-22 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_user_otp_user_otp_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pin',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
