# Generated by Django 4.2.13 on 2025-01-22 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_user_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pin',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
