# Generated by Django 4.2.13 on 2025-01-22 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_user_pin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
    ]
