# Generated by Django 4.2.13 on 2025-02-05 16:16

import datetime
from django.db import migrations, models
import django.db.models.deletion
import school.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('registered_date', models.DateField(auto_now_add=True)),
                ('payment_qr_code', models.FileField(blank=True, null=True, upload_to='payment_qr_code/')),
                ('start', models.TimeField(default=datetime.time(8, 0))),
                ('stop', models.TimeField(default=datetime.time(15, 0))),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_ahead', models.PositiveIntegerField(default=21)),
                ('interval', models.PositiveIntegerField(default=30)),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='school.school')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('no_exp', models.BooleanField()),
                ('exp_range', models.IntegerField(blank=True, null=True)),
                ('duration', models.IntegerField(default=60)),
                ('number_of_lessons', models.IntegerField(default=10)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to=school.models.file_generate_upload_path)),
                ('is_group', models.BooleanField(default=False)),
                ('group_size', models.IntegerField(null=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course', to='school.school')),
            ],
        ),
    ]
