# Generated by Django 4.2.13 on 2025-02-18 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolsettings',
            name='cancel_b4_hours',
            field=models.PositiveIntegerField(default=24),
        ),
    ]
