# Generated by Django 4.2.13 on 2025-02-21 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_schoolsettings_cancel_b4_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolsettings',
            name='teacher_break',
            field=models.PositiveIntegerField(default=15),
        ),
    ]
