# Generated by Django 4.2.13 on 2025-02-21 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_schoolsettings_teacher_break'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolsettings',
            name='school',
        ),
        migrations.AlterField(
            model_name='school',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
