# Generated by Django 4.2.13 on 2025-02-21 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_remove_schoolsettings_school_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='settings',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='school', to='school.schoolsettings'),
        ),
    ]
