# Generated by Django 4.2.13 on 2025-02-22 01:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_facilities'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
