# Generated by Django 4.2.13 on 2025-01-14 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_course_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
