# Generated by Django 4.2.13 on 2025-01-27 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0010_alter_course_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='group_size',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='is_group',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
