# Generated by Django 4.2.13 on 2025-01-27 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0011_course_group_size_course_is_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
