# Generated by Django 4.2.13 on 2025-01-27 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0012_alter_course_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='exp_range',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
