# Generated by Django 4.2.13 on 2025-01-27 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0013_alter_course_exp_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='course_images/'),
        ),
    ]
