# Generated by Django 4.2.13 on 2025-01-27 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0015_school_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='payment_qr_code',
            field=models.FileField(blank=True, null=True, upload_to='payment_qr_code/'),
        ),
    ]
