# Generated by Django 4.2.13 on 2025-01-30 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0016_school_payment_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='is_group',
            field=models.BooleanField(default=False),
        ),
    ]
