# Generated by Django 4.2.13 on 2025-01-31 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0017_alter_course_is_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_ahead', models.PositiveIntegerField(default=21, help_text='Number of days ahead to generate lessons')),
                ('interval', models.PositiveIntegerField(default=30, help_text='Interval between lessons in minutes')),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_settings', to='school.school')),
            ],
        ),
    ]
