# Generated by Django 4.2.13 on 2025-01-31 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0018_schoolsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolsettings',
            name='days_ahead',
            field=models.PositiveIntegerField(default=21),
        ),
        migrations.AlterField(
            model_name='schoolsettings',
            name='interval',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
