# Generated by Django 4.2.13 on 2025-01-31 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0019_alter_schoolsettings_days_ahead_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolsettings',
            name='school',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='school.school'),
        ),
    ]
