# Generated by Django 4.2.13 on 2025-02-18 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('COM', 'Completed'), ('CAN', 'Canceled'), ('MIS', 'Missed')], default='COM', max_length=10),
        ),
    ]
