# Generated by Django 4.2.13 on 2025-01-13 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0033_alter_courseregistration_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseregistration',
            name='discount',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='courseregistration',
            name='paid_price',
            field=models.FloatField(null=True),
        ),
    ]
