# Generated by Django 4.2.13 on 2025-01-17 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0024_alter_teacher_school'),
        ('student', '0034_courseregistration_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestlesson',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guestlesson', to='teacher.teacher'),
        ),
    ]
