# Generated by Django 4.2.13 on 2025-01-22 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0035_alter_guestlesson_teacher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseregistration',
            old_name='used_lessons',
            new_name='lessons_left',
        ),
    ]
