# Generated by Django 4.2.13 on 2025-01-23 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0036_rename_used_lessons_courseregistration_lessons_left'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseregistration',
            name='payment_slip',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='courseregistration',
            name='payment_validated',
            field=models.BooleanField(default=False),
        ),
    ]
