# Generated by Django 4.2.13 on 2025-01-27 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0025_lesson'),
        ('student', '0039_remove_courseregistration_payment_slip_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('student', 'Student'), ('guest', 'Guest')], default='student', max_length=10)),
                ('booked_datetime', models.DateTimeField()),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('canceled', 'Canceled')], default='completed', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('name', models.CharField(max_length=300)),
                ('email', models.CharField(blank=True, max_length=300)),
                ('datetime', models.DateTimeField()),
                ('duration', models.IntegerField()),
                ('code', models.CharField(max_length=12, unique=True)),
                ('notified', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='registration',
        ),
        migrations.DeleteModel(
            name='GuestLesson',
        ),
        migrations.DeleteModel(
            name='Lesson',
        ),
        migrations.AddField(
            model_name='booking',
            name='guest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='student.guest'),
        ),
        migrations.AddField(
            model_name='booking',
            name='lesson',
            field=models.ManyToManyField(related_name='booking', to='teacher.lesson'),
        ),
        migrations.AddField(
            model_name='booking',
            name='registration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='student.courseregistration'),
        ),
        migrations.AddField(
            model_name='booking',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='student.student'),
        ),
    ]
