# Generated by Django 4.2.13 on 2025-01-27 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0025_lesson'),
        ('student', '0040_booking_guest_remove_lesson_registration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='lesson',
        ),
        migrations.AddField(
            model_name='booking',
            name='lesson',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='teacher.lesson'),
            preserve_default=False,
        ),
    ]
