# Generated by Django 4.2.13 on 2025-01-27 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0043_alter_booking_booked_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('COM', 'Completed'), ('CAN', 'Canceled')], default='COM', max_length=10),
        ),
    ]
