# Generated by Django 4.2.13 on 2025-01-27 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0047_booking_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='code',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
