# Generated by Django 4.2.13 on 2025-01-28 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0028_alter_lesson_teacher'),
        ('student', '0048_alter_booking_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseregistration',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registration', to='teacher.teacher'),
        ),
    ]
