# Generated by Django 4.2.13 on 2025-01-31 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0017_alter_course_is_group'),
        ('student', '0049_alter_courseregistration_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseregistration',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registration', to='school.course'),
        ),
    ]
