# Generated by Django 4.2.13 on 2025-02-03 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0050_alter_courseregistration_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentteacherrelation',
            name='student_first_name',
        ),
        migrations.RemoveField(
            model_name='studentteacherrelation',
            name='student_last_name',
        ),
    ]
