# Generated by Django 4.2.13 on 2025-02-03 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0051_remove_studentteacherrelation_student_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='check_in',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='check_out',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
