# Generated by Django 4.2.13 on 2025-02-03 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0052_booking_check_in_booking_check_out'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentteacherrelation',
            name='student_color',
        ),
    ]
